[package]
name = "tetris_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.29.7"
image = "0.23.13"
ggez = "0.9.3"
softbuffer = "0.4.0"
